name: 'Download a Build Artifact which can be ignorable'
description: 'Download a build artifact that was previously uploaded in the workflow by the upload-artifact action'
branding:
  icon: activity
  color: gray-dark
author: 'ThunderMiracle'
inputs: 
  name:
    description: 'Artifact name'
    required: false
  path:
    description: 'Destination path'
    required: false
  if-no-artifact:
    description: 'How to exit action if no artifact is found. Can be fail, warn or ignore'
    default: 'fail'
    required: false
outputs:
  download-path:
    description: 'Path of artifact download'
runs:
  using: 'node16'
  main: 'dist/index.js'
